title:              'タコ'
email:              siberian1000@gmail.com
description:        Hi, I'm takaoka.
author:             takaoka
baseurl:            "/example"
url:                "https://siberian122.github.io"

# Social Profiles
twitter_username:   siberian1yy
github_username:    siberian122
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
